import type { MazeLevel } from "../types/maze";

export const mazeLevels: MazeLevel[] = [
  {
    id: 1,
    name: "逃离小会议室",
    description: "入门教学关，沿着走廊找到电梯口，顺手拿一张摸鱼券。",
    difficulty: 1,
    timeLimitSeconds: 60,
    baseScore: 800,
    map: [
      "WWWWWWWWWWW",
      "WS..T....EW",
      "W.WWWWWWW.W",
      "W.........W",
      "WWWWWWWWWWW",
    ],
    tips: ["墙体不可穿越。", "摸鱼券会提高结算分数。"],
  },
  {
    id: 2,
    name: "开放办公区",
    description: "会议邀请开始出现，咖啡能帮你快速穿过工位区。",
    difficulty: 1,
    timeLimitSeconds: 70,
    baseScore: 900,
    map: [
      "WWWWWWWWWWWWW",
      "WS...M...C.EW",
      "W.WWW.WWWWW.W",
      "W...W.....T.W",
      "WWW.W.WWW.W.W",
      "W.....M.....W",
      "WWWWWWWWWWWWW",
    ],
    tips: ["会议会扣 5 秒。", "咖啡会加速 5 秒。"],
  },
  {
    id: 3,
    name: "Bug 走廊",
    description: "Bug 会拖慢脚步，谨慎选择路线。",
    difficulty: 2,
    timeLimitSeconds: 75,
    baseScore: 1000,
    map: [
      "WWWWWWWWWWWWW",
      "WS..B....T.EW",
      "W.WWW.WWWWW.W",
      "W...W.C...B.W",
      "WWW.W.WWW.W.W",
      "W.....M.....W",
      "WWWWWWWWWWWWW",
    ],
    tips: ["Bug 会让移动速度降低 3 秒。", "高分路线通常更绕。"],
  },
  {
    id: 4,
    name: "需求评审区",
    description: "需求变更会把你送回起点附近，别被临时改稿拖住。",
    difficulty: 2,
    timeLimitSeconds: 80,
    baseScore: 1100,
    map: [
      "WWWWWWWWWWWWWWW",
      "WS....R....T.EW",
      "W.WWWWW.WWWWW.W",
      "W...C...W...M.W",
      "WWW.WWW.W.WWW.W",
      "W...W...W...B.W",
      "W.T...R...C...W",
      "WWWWWWWWWWWWWWW",
    ],
    tips: ["需求变更扣 5 秒并回到起点附近。", "地图里的支路可能藏着摸鱼券。"],
  },
  {
    id: 5,
    name: "老板巡逻线",
    description: "老板开始在走廊巡逻，观察节奏再通过。",
    difficulty: 3,
    timeLimitSeconds: 90,
    baseScore: 1250,
    map: [
      "WWWWWWWWWWWWWWW",
      "WS.....T.....EW",
      "W.WWW.WWW.WWW.W",
      "W...W...C...W.W",
      "WWW.WWW.WWW.W.W",
      "W...M...B.....W",
      "W.WWW.WWW.WWW.W",
      "W.....T.......W",
      "WWWWWWWWWWWWWWW",
    ],
    enemies: [
      {
        id: "boss-5",
        name: "老板",
        icon: "👔",
        path: [
          { row: 3, col: 7 },
          { row: 3, col: 8 },
          { row: 3, col: 9 },
          { row: 3, col: 10 },
          { row: 3, col: 11 },
        ],
        speedMs: 900,
        penaltySeconds: 15,
      },
    ],
    tips: ["碰到老板会扣 15 秒并回到起点。", "巡逻路径不会永久封死通路。"],
  },
  {
    id: 6,
    name: "双会议夹击",
    description: "安全路线和高分路线同时存在，别贪到忘了下班。",
    difficulty: 3,
    timeLimitSeconds: 90,
    baseScore: 1400,
    map: [
      "WWWWWWWWWWWWWWWWW",
      "WS..M...T...B..EW",
      "W.WWW.WWWWW.WWW.W",
      "W.C.W.....W...M.W",
      "WWW.W.WWW.W.WWW.W",
      "W...W...D...W...W",
      "W.WWWWW.WWWWW.W.W",
      "W.T...B...C...T.W",
      "WWWWWWWWWWWWWWWWW",
    ],
    tips: ["免会卡可以抵消一次会议惩罚。", "支路奖励更多，但也更容易被拖慢。"],
  },
  {
    id: 7,
    name: "电梯迷阵",
    description: "更大的办公楼层，死路和奖励支路开始增多。",
    difficulty: 4,
    timeLimitSeconds: 100,
    baseScore: 1600,
    map: [
      "WWWWWWWWWWWWWWWWWWW",
      "WS...W...T.....M.EW",
      "W.W.WW.WWW.WWWWW.WW",
      "W.W....C.W.....W..W",
      "W.WWWWW.W.WWWW.WW.W",
      "W...B...W....W....W",
      "WWW.WWWWWWWW.WWWW.W",
      "W.T.W....R...W..C.W",
      "W.W.W.WWWWWWWW.WW.W",
      "W...W.....T.....B.W",
      "WWWWWWWWWWWWWWWWWWW",
    ],
    tips: ["后期地图更大，格子会自动缩放。", "死路尽头常有额外分数。"],
  },
  {
    id: 8,
    name: "加班楼层",
    description: "老板和项目经理一起巡逻，横纵夹击但仍有窗口期。",
    difficulty: 4,
    timeLimitSeconds: 110,
    baseScore: 1800,
    map: [
      "WWWWWWWWWWWWWWWWWWW",
      "WS...C...W....T..EW",
      "W.WWWWW.W.W.WWWWW.W",
      "W...M...W.W.....B.W",
      "WWW.WWWWW.WWWWW.W.W",
      "W.T...R.....D...W.W",
      "W.WWWWW.WWWWWWW.W.W",
      "W...B...W...C...W.W",
      "W.WWW.WWW.W.WWWWW.W",
      "W.....T...W.......W",
      "WWWWWWWWWWWWWWWWWWW",
    ],
    enemies: [
      {
        id: "boss-8",
        name: "老板",
        icon: "👔",
        path: [
          { row: 5, col: 5 },
          { row: 5, col: 6 },
          { row: 5, col: 7 },
          { row: 5, col: 8 },
          { row: 5, col: 9 },
        ],
        speedMs: 850,
        penaltySeconds: 15,
      },
      {
        id: "pm-8",
        name: "项目经理",
        icon: "📋",
        path: [
          { row: 3, col: 15 },
          { row: 4, col: 15 },
          { row: 5, col: 15 },
          { row: 6, col: 15 },
          { row: 7, col: 15 },
        ],
        speedMs: 1050,
        penaltySeconds: 10,
      },
    ],
    tips: ["不同敌人可以拥有不同巡逻速度。", "先观察，再连续通过。"],
  },
  {
    id: 9,
    name: "周报地狱",
    description: "群消息、会议和 Bug 同时出现，专注力就是生命线。",
    difficulty: 5,
    timeLimitSeconds: 120,
    baseScore: 2100,
    map: [
      "WWWWWWWWWWWWWWWWWWWWW",
      "WS...N...W...T...M.EW",
      "W.WWWWW.W.W.WWWWWWW.W",
      "W...B...W.W...C.....W",
      "WWW.WWWWW.WWWWW.WWW.W",
      "W.T...M...N...W...B.W",
      "W.WWW.WWWWWWW.W.WWW.W",
      "W...W...R...D...W...W",
      "WWW.WWW.WWWWWWWWW.W.W",
      "W.C...B.....T...N...W",
      "WWWWWWWWWWWWWWWWWWWWW",
    ],
    tips: ["群消息扣 3 秒并展示干扰提示。", "免会卡只抵消会议，不抵消其他惩罚。"],
  },
  {
    id: 10,
    name: "终极下班逃生",
    description: "所有机制综合登场，安全慢路线和高风险高分路线都能通关。",
    difficulty: 5,
    timeLimitSeconds: 150,
    baseScore: 2600,
    map: [
      "WWWWWWWWWWWWWWWWWWWWWWW",
      "WS...C...W...T...M...EW",
      "W.WWWWW.W.W.WWWWW.WWW.W",
      "W...B...W.W...R...W...W",
      "WWW.WWWWW.WWWWW.WWW.W.W",
      "W.T...M...N...W...B.W.W",
      "W.WWW.WWWWWWW.W.WWW.W.W",
      "W...W...D...C...W...W.W",
      "WWW.WWW.WWWWWWWWW.WWW.W",
      "W.C...B.....T...N...R.W",
      "W.WWWWWWW.WWWWWWWWWWW.W",
      "W...T.....M.....D.....W",
      "WWWWWWWWWWWWWWWWWWWWWWW",
    ],
    enemies: [
      {
        id: "boss-10",
        name: "老板",
        icon: "👔",
        path: [
          { row: 5, col: 7 },
          { row: 5, col: 8 },
          { row: 5, col: 9 },
          { row: 5, col: 10 },
          { row: 5, col: 11 },
          { row: 5, col: 12 },
        ],
        speedMs: 820,
        penaltySeconds: 15,
      },
      {
        id: "pm-10",
        name: "项目经理",
        icon: "📋",
        path: [
          { row: 7, col: 21 },
          { row: 8, col: 21 },
          { row: 9, col: 21 },
          { row: 10, col: 21 },
          { row: 11, col: 21 },
        ],
        speedMs: 1000,
        penaltySeconds: 10,
      },
    ],
    tips: ["第 10 关通关有额外 2000 分。", "慢路线更稳，高分路线奖励更多。"],
  },
];
